services:
  - type: web
    name: whatsapp-clone-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: whatsapp-clone-backend
          property: port
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard
      - key: CORS_ORIGIN
        sync: false # Set this to your frontend URL
